### ISSUE TITLE
[BUG]: `metadata.json` cannot be written anymore

### ISSUE THREAD

**Issue by chrisgrieser** [kometenstaub/metadata-extractor#17]
Based on the last creation date of a `metadata.json`, it stopped working on March 20th, so I assume the problem is not related to the latest release, but rather to some weird condition that changed in my files.

The other files, `tags.json` and `allExceptMd.json`, still work fine.

This is the log I get with "Show Console Logs" enabled:

```log
app.js:1 Command failed to execute:  metadata-extractor:write-metadata-json
app.js:1 TypeError: Cannot read properties of undefined (reading 'frontmatter')
    at y.writeCacheToJSON (eval at <anonymous> (app.js:1:1444405), <anonymous>:33:2765)
    at Object.callback (eval at <anonymous> (app.js:1:1444405), <anonymous>:33:9951)
    at rz (app.js:1:1565835)
    at e.executeCommandById (app.js:1:1567080)
    at eval (eval at <anonymous> (app.js:1:1444405), <anonymous>:74:11668)
    at e.o [as executeCommandById] (eval at <anonymous> (app.js:1:1444405), <anonymous>:23:77225)
    at T.eval (eval at <anonymous> (app.js:1:1444405), <anonymous>:15:16522)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1444405), <anonymous>:15:363)
    at new Promise (<anonymous>)
e.executeCommandById @ app.js:1
eval @ VM179:74
o @ VM179:23
eval @ VM165:15
eval @ VM165:15
e @ VM165:15
onChooseSuggestion @ VM165:15
eval @ VM165:15
eval @ VM165:15
e @ VM165:15
onChooseSuggestion @ VM165:15
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
```

**Comment by kometenstaub** [comment]
It works for me. :thinking:

**Comment by kometenstaub** [comment]
Hm, then it probably throws off the metadata cache. What happens when you open that file and get the file cache for that file?

**Comment by chrisgrieser** [comment]
how do I do that?

**Comment by chrisgrieser** [comment]
when adding the file to the vault while having the console open, it seems to log this error:

```log
worker.js:1 AppWorker exception RangeError: Maximum call stack size exceeded
    at String.indexOf (<anonymous>)
    at c.e (worker.js:1:88269)
    at c.e (worker.js:1:88339)
    at c.e (worker.js:1:88339)
    at c.e (worker.js:1:88339)
    at c.e (worker.js:1:88339)
    at c.e (worker.js:1:88339)
    at c.e (worker.js:1:88339)
    at c.e (worker.js:1:88339)
    at c.e (worker.js:1:88339)
self.onmessage @ worker.js:1
app.js:1 Metadata failed to parse t {deleted: false, vault: t, path: 'Meta/Autocomplete Dictionary/citekey-autocomplete.md', name: 'citekey-autocomplete.md', basename: 'citekey-autocomplete', …}
```

**Comment by chrisgrieser** [comment]
> ```js
> app.metadataCache.getFileCache(app.workspace.getActiveFile())
> ```

just this:

```js
app.metadataCache.getFileCache(app.workspace.getActiveFile())
undefined
```

**Comment by kometenstaub** [comment]
How many thousand lines does the file have?

**Comment by kometenstaub** [comment]
Ok, I'm checking for `null`, but not undefined https://github.com/obsidianmd/obsidian-api/blob/fc616fa86533d31b1d68b45887f4c9c46da389bf/obsidian.d.ts#L2063
